config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to => 'home#index'

  resources :about, only: [:index]
  resources :lessons, only: [:index]
  resources :music_ed, only: [:index]
  resources :contact, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index

  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @home_page = true
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  def index

  end
end

app/controllers/music_ed_controller.rb
class MusicEdController < ApplicationController
  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/index.html.erb
<body id="about_page">
  <!-- <div id="about-header">
    <h1>About Michelle</h1>
  </div> -->
  <div class="container">
    <div class="row" id="about-body">
      <div class="col-md-3" id="about-left">
      </div>
      <div class="col-md-6" id="about-center">
      </div>
      <div class="col-md-3" id="about-right">
      </div>
    </div>
  </div>
  <div class="container" id="about-text">
    <h3>Michelle is a dedicated and enthusiastic piano teach who enjoys instilling a love of learning the art of music. She believes that music is both a creative and interpretive art. Students will learn how to express themselves through performance, composition and improvisation. They will also learn to appreciate music through age appropriate, engaging lessons in music history and theory. My goal is to provide your student with a lifelong understanding and appreciation of music.</h3>
  </div>

  <div class="footer" id="about-footer">
    <p>&copy; Michelle Dolliver 2018</p>
  </div>
</body>

app/views/contact/index.html.erb
<body id="contact-page">
  <div id="contact-header">
    <h1>Get in touch</h1>
  </div>

  <div class="container">
    <div id="contact-body">
      <h2>To learn more or to schedule a trial lesson, please call or email</h2>
      <h3>360-852-5516 | mdolliver@msn.com</h3>
    </div>
  </div>

  <div class="footer" id="contact-footer">
    <p>&copy; Michelle Dolliver 2018</p>
  </div>
</body>

app/views/home/index.html.erb
<body id="home_page">
  <div id="welcome-img">
  </div>

  <div id="welcome-text">
    <p>michelle dolliver piano studio</p>
    <br>
    <br>
    <h2>Offering private piano lessons to beginning students of all ages near downtown Vancouver, WA</h2>
  </div>

  <div class="container" id="blocks">
    <div class="row">
      <%= link_to lessons_path do %>
        <div class="col-md-6" id="left-block">
          <h2>piano lessons</h2>
        </div>
      <% end %>
      <%= link_to contact_index_path do %>
        <div class="col-md-6" id="right-block">
          <h2>contact me</h2>
        </div>
      <% end %>
    </div>
  </div>

  <div class="container" id="home-block-2">
    <h2>Are you interested in joining the studio?</h2>
    <h3>Feel free to call or email be to schedule an introductory lesson</h3>
    <h3>360-798-0610 | mdolliver@msn.com</h3>
  </div>

  <!-- <div class="container">
    <div class="row" id="home-block-3">
      <div class="col-md-6" id="hb3-left">
        <h3>incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo.</h3>
      </div>
      <div class="col-md-6" id="hb3-right">
        <h3>incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo.</h3>
      </div>
    </div>
  </div> -->

  <!-- <div class="container">
    <div class="row" id="home-block-4">
      <div class="col-md-6" id="hb4-left">
      </div>
      <div class="col-md-6" id="hb4-right">
        <h3>incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo.</h3>
      </div>
    </div>
  </div> -->

  <div class="footer" id="welcome_footer">
    <p>&copy; Michelle Dolliver 2018</p>
  </div>
</body>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container-fluid">
    <div class="navbar-text navbar-left">
      <p>Michelle Dolliver</p>
    </div>
    <div class="navbar-text navbar-right">
      <a><%= link_to 'Home', root_path %></a>
      <a><%= link_to 'About', about_index_path %></a>
      <a><%= link_to 'Lessons', lessons_path %></a>
      <a><%= link_to 'Early Music Education', music_ed_index_path %></a>
      <a><%= link_to 'Contact', contact_index_path %></a>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicTeacher</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render ('layouts/navbar') %>
    <%= yield %>
  </body>
</html>

app/views/lessons/index.html.erb
<body id="lessons-page">
  <div id="lessons-header">
    <h1>With more than 21 years of history, we can tell you this — experience matters because it shows.</h1>
  </div>

  <div class="container">
    <div class="row" id="lessons-block-1">
      <div class="col-md-6" id="lb1-left">
        <h3>Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. </h3>
        <h3>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem.</h3>
      </div>
      <div class="col-md-6" id="lb1-right">
        <h3>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem.</h3>
      </div>
    </div>
  </div>

  <div class="container">
    <div class="row" id="lessons-block-2">
      <div class="col-md-6" id="lb2-left">
        <h3>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem.</h3>
      </div>
      <div class="col-md-6" id="lb2-right">
        <h3>Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. </h3>
        <h3>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem.</h3>
      </div>
    </div>
  </div>

  <div id="lesson-block-3">
    <h1>Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo.</h1>
  </div>

  <div class="footer" id="lessons-footer">
    <p>&copy; Michelle Dolliver 2018</p>
  </div>
</body>

app/views/music_ed/index.html.erb
<body id="music-ed-page">
  <div id="music-ed-header">
    <h1>Music education page</h1>
  </div>

  <div class="container">
    <div class="row" id="music-ed-block-1">
      <div class="col-md-6" id="meb1-left">
        <h3>consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur</h3>
      </div>
      <div class="col-md-6" id="meb1-right">
        <h3>consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur</h3>
      </div>
    </div>
  </div>

  <div class="container" id="music-ed-block-2">

  </div>

  <div class="footer" id="music-ed-footer">
    <p>&copy; Michelle Dolliver 2018</p>
  </div>
</body>